[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dollar_token = "11111111111111111111111111111111"

[programs.devnet]
dollar_token = "11111111111111111111111111111111"

[programs.mainnet]
dollar_token = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metadata.so"

[test.validator]
url = "https://api.devnet.solana.com"
clone = [
  { address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" },
  { address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" },
  { address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" },
]
ledger = "test-ledger"
bind_address = "0.0.0.0"
rpc_port = 8899
